### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [41]:
import random
import numpy as np

vector = np.array([random.uniform(0, 1) for _ in range(10)])
vector2 = np.array(np.random.rand(10))
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print(vector, '\n')
print(vector2, '\n')
print(matrix, '\n')

print('\n')

print('Shape:', vector.shape)
print('Shape:', vector2.shape)
print('Shape:', matrix.shape)

[4.36340566e-01 9.64082017e-01 8.55487032e-04 7.54333108e-01
 2.40193036e-01 9.38033346e-01 1.39002732e-01 1.83480185e-01
 2.41960964e-01 5.94676493e-01] 

[0.6287166  0.13686512 0.20197937 0.24713869 0.65167987 0.48916501
 0.2043998  0.21379302 0.80557126 0.74914733] 

[[11 14 17]
 [20 23 26]
 [29 32 35]] 



Shape: (10,)
Shape: (10,)
Shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
# 1.
sum_vector = np.round(vector + 10, 2)
print(sum_vector, '\n')
# 2.
multiply_matrix = matrix * 2
print(multiply_matrix, '\n')
# 3.
square_vector = np.round(vector ** 2, 4)
print(square_vector, '\n')


[10.86 10.8  10.31 10.   10.88 10.14 10.12 10.72 10.59 10.68]
[[22 28 34]
 [40 46 52]
 [58 64 70]]
[0.7399 0.6397 0.0974 0.     0.7749 0.0192 0.0135 0.5253 0.3492 0.4629]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [25]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [38]:
# 1. B (2x3) @ A (3x2) -> очікую розмірність 2x2
result_matrix = np.dot(B, A)
print(result_matrix, '\n')

# 2. result_matrix (2x2) @ C (2x1) -> очікую вектор-стовпець 2x1
result_matrix_to_c = np.dot(result_matrix, C)
print(result_matrix_to_c, '\n')

# 3. result_matrix (2x2) @ D (2x2) -> очікую матрицю 2x2
result_matrix_to_d = np.dot(result_matrix, D)
print(result_matrix_to_d)

[[0.7281 0.5202]
 [0.2034 0.2846]] 

[[0.5202]
 [0.2846]] 

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
# 1.
result_matrix_t = result_matrix.T
print('result_matrix:')
print(result_matrix, result_matrix.shape, '\n')
print('result_matrix.T:')
print(result_matrix_t, result_matrix_t.shape)
# Висновок: для квадратної матриці форма не змінюється (2x2),
# але елементи дзеркально відображаються відносно головної діагоналі.

# 2. 
vector_t = vector.T
print('vector.shape:', vector.shape)
print('vector.T.shape:', vector_t.shape)
# Висновок: транспонування 1D-масиву НЕ змінює його форму ((10,) -> (10,)).

# 3. expand_dims з axis=1 робить з 1D-вектора вектор-стовпець
column_vector = np.expand_dims(vector, axis=1)
print('column_vector:')
print(column_vector)
print('column_vector.shape:', column_vector.shape)
# Висновок: expand_dims додає нову вісь -> форма стає (10, 1).

# 4. Транспонування column_vector: стовпець -> рядок
row_vector = column_vector.T
print('row_vector:')
print(row_vector)
print('row_vector.shape:', row_vector.shape)
# Висновок: оскільки column_vector двовимірний (10, 1), .T тепер працює
# і перетворює стовпець на рядок (10, 1) -> (1, 10).

result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]] (2, 2) 

result_matrix.T:
[[0.7281 0.2034]
 [0.5202 0.2846]] (2, 2)
vector.shape:     (10,)
vector.T.shape:   (10,)
column_vector:
[[0.86015492]
 [0.79979249]
 [0.31209241]
 [0.00202545]
 [0.88025638]
 [0.13861177]
 [0.11601579]
 [0.72474318]
 [0.59095866]
 [0.68035847]]
column_vector.shape: (10, 1)
row_vector:
[[0.86015492 0.79979249 0.31209241 0.00202545 0.88025638 0.13861177
  0.11601579 0.72474318 0.59095866 0.68035847]]
row_vector.shape: (1, 10)
